### ISSUE TITLE
Cat_plot converts numeric variable to string without warning

### ISSUE THREAD

**Issue by shan-e-s** [cran/interactions#3]
Hi, this isnt really a bug within the package but is a feature that could lead to user error.

Using 'cat_plot' with 2 continuous variables converts the predictor variable into a character variable. This means x axis labels can be very messy as they overlap and its difficult (or maybe impossible) to set breaks so these dont overlap. I had this issue but i eventually realised i should have been using 'interact_plot' instead of 'cat_plot'.

If 'cat_plot' tested for the variables being numeric before plotting and issued a warning that 'interact_plot' is better suited to plotting these variables it might save other users making this same mistake.

Thanks for a great package!

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!
